/* =====================================================================
   File   : 06_Cursor.sql
   Noi dung: 2 CURSOR (moi cursor duoc gom vao 1 Stored Procedure de
             goi lai tu ung dung)
   ===================================================================== */

USE QUANLYTHUVIEN
GO

/* ---------------------------------------------------------------------
   CURSOR 1. Xep loai muc do uy tin cua doc gia.
   Tao bang DOCGIA_XEPLOAI(MADG, SOLUOTMUON, SOLANTRE, SOLANHUMAT,
                           TONGTIENPHAT, XEPLOAI).
   Duyet tung doc gia, tinh cac chi so va xep loai:
     + "Uy tín"     : co muon sach, khong tre / hu / mat lan nao
     + "Bình thường": tre toi da 1 lan, khong hu / mat
     + "Cảnh báo"   : tre tu 2 lan tro len hoac co lam hu sach
     + "Hạn chế"    : co lam mat sach hoac dang no tren 100.000d
     + "Chưa mượn"  : chua muon lan nao
   --------------------------------------------------------------------- */
IF OBJECT_ID('DOCGIA_XEPLOAI') IS NOT NULL
	DROP TABLE DOCGIA_XEPLOAI
GO

CREATE TABLE DOCGIA_XEPLOAI
(
	MADG			CHAR(5)			PRIMARY KEY FOREIGN KEY REFERENCES DOCGIA (MADG),
	SOLUOTMUON		INT				NOT NULL,
	SOLANTRE		INT				NOT NULL,
	SOLANHUMAT		INT				NOT NULL,
	TONGTIENPHAT	MONEY			NOT NULL,
	XEPLOAI			NVARCHAR(20)	NOT NULL,
	NGAYCAPNHAT		DATETIME		NOT NULL DEFAULT GETDATE()
)
GO

CREATE PROCEDURE SP_CURSOR_XEPLOAIDOCGIA
AS
BEGIN
	SET NOCOUNT ON

	DELETE FROM DOCGIA_XEPLOAI

	DECLARE @MADG CHAR(5), @TONGNO MONEY
	DECLARE @SOLUOT INT, @SOTRE INT, @SOHUMAT INT, @SOMAT INT, @TIENPHAT MONEY
	DECLARE @XEPLOAI NVARCHAR(20)

	DECLARE CUR_DOCGIA CURSOR FOR
		SELECT MADG, TONGNO FROM DOCGIA

	OPEN CUR_DOCGIA
	FETCH NEXT FROM CUR_DOCGIA INTO @MADG, @TONGNO

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- So luot sach da muon
		SELECT @SOLUOT = COUNT(*)
		FROM CTPHIEUMUON CT JOIN PHIEUMUON PM ON CT.MAPM = PM.MAPM
		WHERE PM.MADG = @MADG

		-- So lan tra tre (da tra tre hoac dang giu qua han)
		SELECT @SOTRE = COUNT(*)
		FROM CTPHIEUMUON CT JOIN PHIEUMUON PM ON CT.MAPM = PM.MAPM
		WHERE PM.MADG = @MADG
		  AND ((CT.NGAYTRA IS NOT NULL AND CT.NGAYTRA > PM.HANTRA)
			OR (CT.NGAYTRA IS NULL AND PM.HANTRA < CAST(GETDATE() AS DATE)))

		-- So lan lam hu / mat sach
		SELECT @SOHUMAT = COUNT(*),
			   @SOMAT = ISNULL(SUM(CASE WHEN CT.TINHTRANGTRA = N'Mất' THEN 1 ELSE 0 END), 0)
		FROM CTPHIEUMUON CT JOIN PHIEUMUON PM ON CT.MAPM = PM.MAPM
		WHERE PM.MADG = @MADG AND CT.TINHTRANGTRA IN (N'Hư hỏng', N'Mất')

		-- Tong tien phat (ca da va chua thanh toan)
		SELECT @TIENPHAT = ISNULL(SUM(PP.SOTIEN), 0)
		FROM PHIEUPHAT PP JOIN PHIEUMUON PM ON PP.MAPM = PM.MAPM
		WHERE PM.MADG = @MADG

		SET @XEPLOAI = CASE
			WHEN @SOLUOT = 0							THEN N'Chưa mượn'
			WHEN @SOMAT > 0 OR @TONGNO > 100000			THEN N'Hạn chế'
			WHEN @SOTRE >= 2 OR @SOHUMAT > 0			THEN N'Cảnh báo'
			WHEN @SOTRE = 1								THEN N'Bình thường'
			ELSE N'Uy tín'
		END

		INSERT INTO DOCGIA_XEPLOAI (MADG, SOLUOTMUON, SOLANTRE, SOLANHUMAT, TONGTIENPHAT, XEPLOAI)
		VALUES (@MADG, @SOLUOT, @SOTRE, @SOHUMAT, @TIENPHAT, @XEPLOAI)

		FETCH NEXT FROM CUR_DOCGIA INTO @MADG, @TONGNO
	END

	CLOSE CUR_DOCGIA
	DEALLOCATE CUR_DOCGIA

	SELECT XL.MADG, DG.HOTEN, XL.SOLUOTMUON, XL.SOLANTRE, XL.SOLANHUMAT, XL.TONGTIENPHAT, XL.XEPLOAI
	FROM DOCGIA_XEPLOAI XL JOIN DOCGIA DG ON XL.MADG = DG.MADG
	ORDER BY XL.MADG
END
GO

/* ---------------------------------------------------------------------
   CURSOR 2. Lap danh sach nhac nho doc gia giu sach qua han.
   Tao bang NHACNHO_QUAHAN(MANN, MAPM, MACS, MADG, HOTEN, SODT, TENDS,
                           HANTRA, SONGAYTRE, TIENPHATTAMTINH, NOIDUNG, NGAYLAP).
   Tham so vao: ngay kiem tra (mac dinh hom nay).
   Duyet tung cuon sach chua tra va da qua han, tinh so ngay tre, tien
   phat tam tinh (FN_TIENPHATTRE) va soan noi dung tin nhan nhac nho.
   Cuon sach da duoc nhac trong cung ngay thi khong them lai.
   --------------------------------------------------------------------- */
IF OBJECT_ID('NHACNHO_QUAHAN') IS NOT NULL
	DROP TABLE NHACNHO_QUAHAN
GO

CREATE TABLE NHACNHO_QUAHAN
(
	MANN			INT				IDENTITY(1,1) PRIMARY KEY,
	MAPM			CHAR(6)			NOT NULL,
	MACS			CHAR(5)			NOT NULL,
	MADG			CHAR(5)			NOT NULL FOREIGN KEY REFERENCES DOCGIA (MADG),
	HOTEN			NVARCHAR(40)	NOT NULL,
	SODT			VARCHAR(15)		NOT NULL,
	TENDS			NVARCHAR(100)	NOT NULL,
	HANTRA			DATE			NOT NULL,
	SONGAYTRE		INT				NOT NULL,
	TIENPHATTAMTINH	MONEY			NOT NULL,
	NOIDUNG			NVARCHAR(300)	NOT NULL,
	NGAYLAP			DATE			NOT NULL,
	FOREIGN KEY (MAPM, MACS) REFERENCES CTPHIEUMUON (MAPM, MACS)
)
GO

CREATE PROCEDURE SP_CURSOR_NHACNHOQUAHAN
	@NGAYKIEMTRA DATE = NULL
AS
BEGIN
	SET NOCOUNT ON
	IF @NGAYKIEMTRA IS NULL
		SET @NGAYKIEMTRA = CAST(GETDATE() AS DATE)

	DECLARE @MAPM CHAR(6), @MACS CHAR(5), @MADG CHAR(5), @HOTEN NVARCHAR(40),
			@SODT VARCHAR(15), @TENDS NVARCHAR(100), @HANTRA DATE
	DECLARE @SONGAYTRE INT, @TIENPHAT MONEY, @NOIDUNG NVARCHAR(300)
	DECLARE @SODONG INT = 0

	DECLARE CUR_QUAHAN CURSOR FOR
		SELECT PM.MAPM, CT.MACS, DG.MADG, DG.HOTEN, DG.SODT, DS.TENDS, PM.HANTRA
		FROM CTPHIEUMUON CT
			JOIN PHIEUMUON PM ON CT.MAPM = PM.MAPM
			JOIN DOCGIA DG ON PM.MADG = DG.MADG
			JOIN CUONSACH CS ON CT.MACS = CS.MACS
			JOIN DAUSACH DS ON CS.MADS = DS.MADS
		WHERE CT.NGAYTRA IS NULL AND PM.HANTRA < @NGAYKIEMTRA
		ORDER BY PM.HANTRA

	OPEN CUR_QUAHAN
	FETCH NEXT FROM CUR_QUAHAN INTO @MAPM, @MACS, @MADG, @HOTEN, @SODT, @TENDS, @HANTRA

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF NOT EXISTS (SELECT * FROM NHACNHO_QUAHAN
					   WHERE MAPM = @MAPM AND MACS = @MACS AND NGAYLAP = @NGAYKIEMTRA)
		BEGIN
			SET @SONGAYTRE = DATEDIFF(DAY, @HANTRA, @NGAYKIEMTRA)
			SET @TIENPHAT = dbo.FN_TIENPHATTRE(@HANTRA, @NGAYKIEMTRA)
			SET @NOIDUNG = N'Thư viện thông báo: bạn ' + @HOTEN + N' đang giữ sách "' + @TENDS
						 + N'" quá hạn ' + CAST(@SONGAYTRE AS NVARCHAR(10)) + N' ngày (hạn trả '
						 + CONVERT(NVARCHAR(10), @HANTRA, 103) + N'). Tiền phạt tạm tính: '
						 + FORMAT(@TIENPHAT, 'N0') + N'đ. Vui lòng trả sách sớm.'

			INSERT INTO NHACNHO_QUAHAN (MAPM, MACS, MADG, HOTEN, SODT, TENDS, HANTRA,
										SONGAYTRE, TIENPHATTAMTINH, NOIDUNG, NGAYLAP)
			VALUES (@MAPM, @MACS, @MADG, @HOTEN, @SODT, @TENDS, @HANTRA,
					@SONGAYTRE, @TIENPHAT, @NOIDUNG, @NGAYKIEMTRA)

			SET @SODONG = @SODONG + 1
		END

		FETCH NEXT FROM CUR_QUAHAN INTO @MAPM, @MACS, @MADG, @HOTEN, @SODT, @TENDS, @HANTRA
	END

	CLOSE CUR_QUAHAN
	DEALLOCATE CUR_QUAHAN

	PRINT N'Đã tạo ' + CAST(@SODONG AS NVARCHAR(10)) + N' nhắc nhở mới.'

	SELECT * FROM NHACNHO_QUAHAN WHERE NGAYLAP = @NGAYKIEMTRA ORDER BY SONGAYTRE DESC
END
GO

/* ---------------------- VI DU SU DUNG ------------------------------
EXEC SP_CURSOR_XEPLOAIDOCGIA
EXEC SP_CURSOR_NHACNHOQUAHAN '2026-09-26'
--------------------------------------------------------------------- */
